---
profiles::nginx::proxy::templates:
  '/etc/nginx/templates/puppetboard.ctmpl':
    content: |
      upstream pupperboard_backend {
      {{range service "puppetboard"}}
       server {{.Address}}:{{.Port}};
      {{end}}
      }

      server {
        listen *:80;
        server_name           puppetboard.renorains.net;
        client_max_body_size 256M;

        index  index.html index.htm index.php;

        access_log            /var/log/nginx/puppetboard.access.log combined;
        error_log             /var/log/nginx/puppetboard.error.log;

        location /healthcheck {

          return 200;
        }

        location / {

          proxy_pass            http://pupperboard_backend;
          proxy_read_timeout    1800;
          proxy_connect_timeout 1800;
          proxy_redirect        off;
          proxy_set_header      Host $host;
          proxy_set_header      X-Real-IP $remote_addr;
          proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
