---
consul::services:
  puppetdb:
    address: "%{::ipaddress_eth0}"
    checks:
      - script: "curl -k https://%{::ipaddress_eth0}:8081 >/dev/null 2>&1"
        interval: 10s
    port: 8081
    tags:
      - "puppetdb"
