---
profiles::puppetdb::vhosts::vhosts:
  'puppetdb.service.ew1.consul':
    #listen_port: '8081'
    proxy: 'http://localhost:8080'
    listen_ip: "%{scope('::ipaddress_eth0')}"
    ssl: true
    ssl_cert: '/etc/puppetlabs/puppetdb/ssl/public.pem'
    ssl_key: '/etc/puppetlabs/puppetdb/ssl/private.pem'
    ssl_port: 8081
profiles::puppetdb::vhosts::cert_content: |
  -----BEGIN CERTIFICATE-----
  MIIDdTCCAl2gAwIBAgIJAO7jljt905psMA0GCSqGSIb3DQEBCwUAMFExCzAJBgNV
  BAYTAlVLMQ8wDQYDVQQIDAZMb25kb24xDzANBgNVBAcMBkxvbmRvbjETMBEGA1UE
  CgwKTXkgQ29tcGFueTELMAkGA1UECwwCSVQwHhcNMTYxMDA2MjE1NzQ5WhcNMTYx
  MTA1MjE1NzQ5WjBRMQswCQYDVQQGEwJVSzEPMA0GA1UECAwGTG9uZG9uMQ8wDQYD
  VQQHDAZMb25kb24xEzARBgNVBAoMCk15IENvbXBhbnkxCzAJBgNVBAsMAklUMIIB
  IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2SDdnRgkZhzrp6g6TWJSsqsB
  HB2mhSoga0xCFuiOuNhi7M1nTxbwzjJ+q6Fq0Q0D2WXBhlLgnyJsyWQFD8KM/Hk3
  LFrWV3wkCzEocu2/PjdkJSXg7Kve9Khna0yofXhX1NMwer0Wy7EyWtaYXPWfCkgX
  LHwaQIc4mtQ6J7fz/3E0duMJx/h3bQabgMqkV34Jyr6g/icnxrYcRl24TUWIarKk
  H1NCUUMM4O6938ixS9T2A7SkWIr5V5dEupWExLFYSVy/JGBUrGT0FrZQ8qlkW8G4
  cWwFWawaEBqLIuvP6NT2npRGVVhKYFdmp5MtruPO+Jf4HbLxUFQcMG5D9/UufQID
  AQABo1AwTjAdBgNVHQ4EFgQUp4HYmziE6JkBvUMJArTfQ30uXRcwHwYDVR0jBBgw
  FoAUp4HYmziE6JkBvUMJArTfQ30uXRcwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0B
  AQsFAAOCAQEAFrF4AslDxTgwIIdhyEjPKqdbpWPL4JrGfqQgsGhf/x55M9XvHLHt
  5XqF7mf4tMPNe4WUtj93dvtKWt50A+qZRdd864zkihyOXU4CNm0kuwobn0mMSEqn
  smcfGsD/mOQs1Awk6Bj257gp47uBaO/XWo4BBa8ys1XmovQyFmdT+rKAS1TFOy9m
  ewDNGxWyPlI6XeEmypf/D11p6iSTXsyrnXpBHoMwPx7YFrpUypbFG0GL2yCHrvro
  fXZkCM014ZhO9e/nuHMbtVGLfwQCemKeX/W2/ozbSv7XSAERD4lE84bzSrv3Adgj
  tiq1JOjr/I7vuECATffXQvHbThaRfxxo2g==
  -----END CERTIFICATE-----
profiles::puppetdb::vhosts::key_content: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEA2SDdnRgkZhzrp6g6TWJSsqsBHB2mhSoga0xCFuiOuNhi7M1n
  TxbwzjJ+q6Fq0Q0D2WXBhlLgnyJsyWQFD8KM/Hk3LFrWV3wkCzEocu2/PjdkJSXg
  7Kve9Khna0yofXhX1NMwer0Wy7EyWtaYXPWfCkgXLHwaQIc4mtQ6J7fz/3E0duMJ
  x/h3bQabgMqkV34Jyr6g/icnxrYcRl24TUWIarKkH1NCUUMM4O6938ixS9T2A7Sk
  WIr5V5dEupWExLFYSVy/JGBUrGT0FrZQ8qlkW8G4cWwFWawaEBqLIuvP6NT2npRG
  VVhKYFdmp5MtruPO+Jf4HbLxUFQcMG5D9/UufQIDAQABAoIBAFvicqZGTzD/UCKV
  KIcS8tg1UbTqP0vfNfTyQo2bQLqsp8B6dBueI62+5KgRGTj6fwSC8VC8xd3SHaNk
  NlgjBrLZQSX+EvLW0BIEbY+lWOclXbXyv6qoWSPEGG/p8uuV/+VKshte5cSxahPS
  +ItuTi11sIjcw+dG0geDhFDGofUY1X5Eauf2hEdVBviIgdub/sUHh22Kp/muQbkg
  /DsaB26iGfGTAE/GMSfh7vhNtZ9JhGMaUFCSK97w5GR3/sQhryzEZz1ZYj5nWwC4
  YVBDBBgH0/lp4BvO4OvmMQJkjLYlrBQo5bd9H46fmQveht/VwAXiea9zWJCIbJ0k
  azEbwWkCgYEA776W3Pq9nCofOVxrdepiK5d+gHPHw/pWEcIpK9cpKeZ0elq8Z+k+
  pFF9szwDjWwbQyifKLKlZ2dRmACYodElGPRXgvbKdGipbgyPAuwLYjMLrFQwZOsY
  nxRDp+u7CZeSLSj5d2rpv+z0+GFhyIC1sXB2E3RUFIgFdJsy2v9PnYcCgYEA59m2
  hL8vtCmB/gNeQTM3WmDm6zvDtj4TLLGOwWgwUhrHZcm2dagu7yjTIs2YvewtFWB+
  63C0sxDiyOdve0qISN9Q/9S+soBhg0URjquxe0qDnI+QWVwRp76mKQxrlN9HTs4w
  xNUZ+rcIo5hBpxCQEjyoqcV6L0lEb192vazWNNsCgYEAwObdhJjMD+dkkEbowEwD
  CYgv5TNDvVCkCE3tyrSpDmm7tudjSUjHeneHaLwVL6mYlgUNazWzGOxtHpz8MteR
  ve58q4ffhqLgEQhR2cwLrMvdzJ9BATKY8QbhGS/3otQubd/WOlvwENmckm3ou+e0
  Sj1vBGBJduurWBO4a7WaXekCgYAblV5OmsRdJdcOVm4/SY2bVg4DDIAzTV1Qous9
  /VxKWF9Cr+XiR5kV4QCFknpKli+i7HENJ8KHz0l753Tu8SYXrWHgnfn2GKoBSRVW
  qPybk3jnBnmA+CAtmdQA7DZcZtf/+y34LPZDSsVfWTzuWF0bnlXepNzthUT8Dxp8
  ZHSzowKBgBkY85DTntHiQ336BL1Mzd/KB9K7An3nhyc1Io8+mYfrDJqhbfBEpbW5
  MV0x9d4robpPwOgbDx8qqLLMziN62YCZjIIasuK+URANxqUQa6OZqVvCyTgASwnO
  Kajc79T3zKxlwmgjWF9ADflWDvBAS1ZTSwvXjIYhEayu25cd3hVC
  -----END RSA PRIVATE KEY-----
